# Generated by Django 3.1.1 on 2020-12-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_name', models.CharField(default='Bracket Name', max_length=500)),
                ('primary_contact_type', models.CharField(default='Email', max_length=500)),
                ('primary_contact_value', models.CharField(blank=True, default='Jenna', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tournament_description', models.CharField(default='A new tournament.', max_length=30000)),
                ('location', models.CharField(default='Online', max_length=500)),
            ],
        ),
    ]
